version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.3
    commands:
      - yum update -y
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - yum install -y libzip-devel
      - curl -sS https://getcomposer.org/installer -o composer-setup.php
      - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
      - touch ~/database/database.sqlite
  pre_build:
    commands:
      - composer install
      - npm install
artifacts:
  files:
    - '**/*'
  name: $(date +%Y-%m-%dT%H:%M:%S).zip
proxy:
  upload-artifacts: yes
  logs: yes
